services:
  - type: web
    name: fxql-api
    runtime: docker
    branch: main
    plan: free
    healthCheckPath: /app/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_KEY
        generateValue: true